name: rth_genaith
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - annotated-types=0.7.0
  - anyio=4.12.1
  - async-timeout=4.0.3
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - cpython=3.12.12
  - distro=1.9.0
  - exceptiongroup=1.3.1
  - expat=2.7.4
  - frozenlist=1.7.0
  - greenlet=3.3.1
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.11
  - jiter=0.13.0
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - langchain=1.2.10
  - langchain-core=1.2.11
  - langchain-text-splitters=0.3.11
  - langgraph=1.0.8
  - langgraph-checkpoint=4.0.0
  - langgraph-prebuilt=1.0.7
  - langgraph-sdk=0.3.5
  - langsmith=0.7.1
  - ld_impl_linux-64=2.44
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.11.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - multidict=6.7.0
  - ncurses=6.5
  - numpy=2.4.2
  - openai=2.20.0
  - openssl=3.6.1
  - ormsgpack=1.12.2
  - packaging=25.0
  - pandas=3.0.0
  - pip=26.0.1
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pycparser=2.22
  - pydantic=2.12.5
  - pydantic-core=2.41.5
  - pysocks=1.7.1
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python-xxhash=3.6.0
  - python_abi=3.12
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - setuptools=80.10.2
  - six=1.17.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.46
  - sqlite=3.51.1
  - tenacity=9.1.4
  - tk=8.6.15
  - tqdm=4.67.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - uuid-utils=0.14.0
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.3
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - langchain-openai==1.1.9
      - orjson==3.11.7
      - regex==2026.1.15
      - tiktoken==0.12.0
      - zstandard==0.25.0
prefix: /home/ramizk/miniconda3/envs/rth_genaith
